local_costmap:
  #global_frame: odom
  #robot_base_frame: base_link
  update_frequency: 2.0
  publish_frequency: 1.0
  rolling_window: true
  width: 0.5
  height: 0.5
  resolution: 0.1
  static_map: true